### ISSUE TITLE
[map] displaying as black screen

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7754]
![image](https://github.com/user-attachments/assets/d5200498-1c1a-46a9-b3d4-3b40aca78460)

**Comment by wittjosiah** [comment]
This should be resolved in 0.6.10

**Comment by seagreen** [comment]
I hope this isn't a "my machine" issue, but I'm still seeing the problem (in an incognito window on latest `main`).

Visually what's shown has changed, it's now blank instead of the black rectangle:

![image](https://github.com/user-attachments/assets/89db7a96-d7c1-402d-8adb-97f70b06303d)
